// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "InnerCompass",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Inner Compass",
            targets: ["AppModule"],
            bundleIdentifier: "com.arturoalfani.InnerCompass",
            teamIdentifier: "U6452PB59V",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.yellow),
            supportedDeviceFamilies: [
                .pad
            ],
            supportedInterfaceOrientations: [
                .landscapeRight,
                .landscapeLeft
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: "."
        )
    ]
)
